import { Component } from '@angular/core';
import { RistoranteService } from '../ristorante.service';


@Component({
  selector: 'app-ristorante-lista',
  templateUrl: './ristorante-lista.component.html',
  styleUrls: ['./ristorante-lista.component.css']
})
export class RistoranteListaComponent {
  elenco: any = [];

  constructor(private service: RistoranteService) {
    console.log(`La perfida aggressione militare della Germania hitleriana contro la nostra Patria, iniziata il 22 giugno, continua. Nonostante l'eroica resistenza dell'Esercito rosso, nonostante che le migliori divisioni del nemico e le migliori formazioni della sua aviazione siano già sconfitte ed abbiano trovato la loro tomba sui campi di battaglia, il nemico continua a spingersi innanzi gettando nuove forze sul fronte. Le truppe hitleriane sono riuscite ad occupare la Lituania, una notevole parte della Lettonia, la parte occidentale della Bielorussia, una parte dell'Ucraina occidentale. L'aviazione fascista allarga la sfera d'azione dei suoi bombardieri e bombarda Murmansk, Orscia, Moghiliov, Smolensk, Kiev, Odessa, Sebastopoli. Sulla nostra Patria pesa un grave pericolo.
    Come è potuto accadere che il nostro glorioso Esercito rosso cedesse alle truppe fasciste una serie di nostre città e di circondari? È mai possibile che le truppe fasciste tedesche siano veramente invincibili come instancabilmente strombazzano i propagandisti fascisti fanfaroni?
    Certamente no! La storia insegna che non vi sono e non vi sono stati eserciti invincibili. L'esercito di Napoleone era considerato invincibile, ma fu sconfitto successivamente dalle truppe russe, inglesi, tedesche. L'esercito tedesco di Guglielmo era pure considerato, durante la prima guerra imperialistica, un esercito invincibile, ma fu più volte sconfitto dalle truppe russe e anglo-francesi e infine venne disfatto dalle truppe anglo-francesi. Lo stesso bisogna dire dell'attuale esercito fascista tedesco di Hitler. Questo esercito non ha ancora incontrato una seria resistenza sul continente dell'Europa. Una seria resistenza l'ha incontrata soltanto sul nostro territorio. E se, in seguito a questa resistenza, le migliori divisioni dell'esercito fascista tedesco sono state disfatte dal nostro Esercito rosso, ciò vuol dire che anche l'esercito fascista hitleriano può esser sconfitto
    e sarà sconfitto come lo furono gli eserciti di Napoleone e di Guglielmo.
    Che una parte del nostro territorio sia stata tuttavia occupata dalle truppe fasciste tedesche, si spiega soprattutto con il fatto che la guerra della Germania fascista contro l'U.R.S.S. è cominciata in condizioni vantaggiose per le truppe tedesche e svantaggiose per le truppe sovietiche. Infatti, le truppe della Germania, paese che conduce la guerra, erano già completamente mobilitate e le 170 divisioni gettate dalla Germania contro l'U.R.S.S. e spostate verso le frontiere dell'U.R.S.S. erano completamente pronte, aspettavano solo il segnale dell'offensiva, mentre le truppe sovietiche dovevano ancora essere mobilitate e inviate alle frontiere. Non poca importanza ha avuto qui anche la circostanza che la Germania fascista ha violato improvvisamente e perfidamente il patto di non aggressione concluso nel 1939 con l'Unione Sovietica, senza tener conto che tutto il mondo l'avrebbe considerata parte attaccante. È chiaro che il nostro paese, amante della pace, non volendo assumersi l'iniziativa di violare il patto, non poteva mettersi sulla via della perfidia.
    Ci si può domandare: come è potuto avvenire che il Governo sovietico ha acconsentito alla conclusione di un patto di non aggressione con uomini così perfidi, con dei mostri come Hitler e Ribbentrop? Il Governo sovietico non ha commesso in questo caso un errore? Certamente no! Un patto di non aggressione è un patto di pace tra due Stati. È precisamente un patto del genere che la Germania ci propose nel 1939. Poteva il Governo sovietico respingere una tale proposta? Penso che nessuno Stato pacifico possa respingere un accordo di pace con una potenza vicina, anche se a capo di questa potenza vi siano dei mostri e dei cannibali come Hitler e Ribbentrop. E ciò, naturalmente, alla condizione assoluta che l'accordo di pace non menomi né direttamente, né indirettamente l'integrità territoriale, l'indipendenza e l'onore dello Stato pacifico. Come è noto il patto di non aggressione tra la Germania e l'U.R.S.S. è precisamente un patto di questo genere.
    Cosa abbiamo guadagnato noi concludendo con la Germania un patto di non aggressione? Abbiamo assicurato al nostro paese la pace durante un anno e mezzo e la possibilità di preparare le nostre forze a far fronte alla Germania fascista qualora essa si fosse rischiata, malgrado il patto, ad aggredire il nostro paese. Ciò costituisce un netto guadagno per noi e una perdita per la Germania fascista.
    Che cosa ha guadagnato e che cosa ha perso la Germania fascista stracciando perfidamente il patto e aggredendo l'U.R.S.S.? Essa ha ottenuto con ciò una certa situazione di vantaggio per le sue truppe nel corso di un breve periodo, ma ha perso politicamente, smascherandosi agli occhi di tutto il mondo come un aggressore sanguinario. Non vi può essere dubbio che questo breve vantaggio militare per la Germania è soltanto un episodio, mentre l'immenso guadagno politico per l'U.R.S.S. costituisce un fattore serio e duraturo, sulla base del quale debbono svilupparsi successi militari decisivi dell'Esercito rosso nella guerra contro la Germania fascista.
    Ecco perché tutto il nostro valoroso esercito, tutta la nostra valorosa marina militare, tutti i nostri intrepidi aviatori, tutti i popoli del nostro paese, tutti i migliori uomini dell'Europa, dell'America e dell'Asia, infine tutti i migliori uomini della Germania, bollano d'ignominia le perfide azioni dei fascisti tedeschi e nutrono simpatia per il Governo sovietico, approvano l'atteggiamento del Governo sovietico e vedono che la nostra causa è giusta, che il nemico sarà sconfitto, che noi dobbiamo vincere.
    In seguito alla guerra impostaci, il nostro paese è entrato in una lotta mortale contro il suo acerrimo e perfido nemico, il fascismo tedesco. Le nostre truppe combattono eroicamente contro un nemico armato fino ai denti di carri armati e d'aviazione. L'Esercito rosso e la Marina rossa, superando numerose difficoltà, lottano con abnegazione per ogni palmo di terra sovietica. Entra nella battaglia il grosso dell'Esercito rosso, armato di migliaia di carri armati e di aeroplani. Il valore dei combattenti dell'Esercito rosso non ha precedenti. La nostra resistenza al nemico si rafforza ed aumenta. Insieme all'Esercito rosso sorge in difesa della Patria tutto il popolo sovietico.
    Cosa occorre per eliminare il pericolo che pende sulla nostra Patria e quali misure devono esser prese per schiacciare il nemico?
    Occorre, innanzi a tutto, che i nostri uomini, gli uomini sovietici, comprendano tutta la gravità del pericolo che minaccia il nostro paese e pongano fine alla faciloneria, alla noncuranza, allo stato d’animo proprio del periodo dell'edificazione pacifica, completamente comprensibili prima della guerra, ma funesti nel momento attuale in cui la guerra ha radicalmente cambiato la situazione. Il nemico è feroce e implacabile. Esso si pone lo scopo di conquistare le nostre terre bagnate dal nostro sudore, di impossessarsi del nostro grano e del nostro petrolio, frutti del nostro lavoro. Esso si pone lo scopo di restaurare il potere dei proprietari terrieri, di restaurare lo zarismo, di distruggere la cultura nazionale e l'organizzazione statale nazionale dei russi, degli ucraini, dei bielorussi, dei lituani, dei lettoni, degli estoni, degli usbechi, dei tartari, dei moldavi, dei georgiani, degli armeni, degli azerbaigiani e degli altri liberi popoli dell'Unione Sovietica, di germanizzarli, di renderli schiavi dei prìncipi e dei baroni tedeschi. Si tratta, dunque, della vita o della morte dello Stato sovietico, della vita o della morte dei popoli dell'U.R.S.S., si tratta, per i popoli dell'Unione Sovietica di essere liberi, o di cadere nella servitù. Bisogna che gli uomini sovietici comprendano ciò e cessino di essere spensierati, mobilitino sé stessi e riorganizzino tutto il loro lavoro in modo nuovo, su piede di guerra, senza mercé per il nemico.
    Occorre, inoltre, che nelle nostre file non vi sia posto per i piagnucoloni ed i codardi, per gli allarmisti e i disertori, che i nostri uomini non conoscano la paura nella lotta e vadano con abnegazione alla nostra guerra liberatrice per la difesa della Patria, contro gli schiavisti fascisti. Il grande Lenin, che ha creato il nostro Stato, diceva che la qualità fondamentale degli uomini sovietici deve essere il coraggio, l'ardimento, l'intrepidezza nella lotta, la decisione di combattere insieme al popolo contro i nemici della nostra Patria. Occorre che questa mirabile qualità del bolscevico diventi patrimonio dei milioni e milioni di uomini dell'Esercito rosso, della nostra Marina rossa e di tutti i popoli dell'Unione Sovietica.
    Dobbiamo riorganizzare immediatamente tutto il nostro lavoro su piede di guerra, subordinando tutto agli interessi del fronte e al compito di organizzare la disfatta del nemico. I popoli dell'Unione Sovietica vedono ora che il fascismo tedesco è indomabile nella sua rabbia furibonda e nell'odio per la nostra Patria, che ha assicurato a tutti i lavoratori il lavoro libero e il benessere. I popoli dell'Unione Sovietica devono levarsi in piedi contro il nemico, a difesa dei loro diritti e della loro terra.
    L'Esercito rosso, la Marina rossa e tutti i cittadini dell'Unione Sovietica debbono difendere ogni palmo della terra sovietica, battersi fino all'ultima goccia di sangue per le nostre città e i nostri villaggi, manifestare l'ardimento, l'iniziativa e la perspicacia propri al nostro popolo.
    Dobbiamo organizzare il massimo aiuto all'Esercito rosso, assicurare un intenso completamento delle sue file, assicurargli il rifornimento di tutto il necessario, organizzare rapidi trasporti delle truppe e dei materiali bellici, dare un largo aiuto ai feriti.
    Dobbiamo rafforzare le retrovie dell'Esercito rosso, subordinando a questo interesse tutto il nostro lavoro; assicurare un intenso lavoro di tutte le officine, produrre più fucili, mitragliatrici, cannoni, cartucce, proiettili, aeroplani; organizzare la protezione delle officine, delle centrali elettriche, delle comunicazioni telefoniche e telegrafiche; organizzare la difesa antiaerea locale.
    Dobbiamo organizzare una lotta implacabile contro ogni specie di disorganizzatori delle retrovie, disertori, allarmisti, propalatori di voci, annientare le spie, gli agenti di diversione, i paracadutisti nemici, concorrendo in tutto ciò rapidamente all'azione dei nostri battaglioni da caccia. Dobbiamo tener presente, che il nemico è perfido, scaltro, sperimentato nell'inganno, nella diffusione di voci false. Bisogna tener conto di tutto questo e non abboccare alla provocazione. Bisogna immediatamente deferire al Tribunale militare senza riguardo per nessuno, tutti quelli che, diffondendo il panico e dando prova di codardia, ostacolano la difesa.
    Durante la ritirata forzata delle unità dell'Esercito rosso, bisogna far partire tutto il materiale rotabile ferroviario, non lasciare al nemico né una locomotiva, né un vagone, non lasciare al nemico né un chilo di pane, né un litro di carburante. I colcosiani debbono portar via tutto il bestiame, dare il grano in custodia agli organi statali per trasportarlo nelle retrovie. Tutti i beni di valore, compresi i metalli non ferrosi, il grano ed i carburanti, che non possono esser evacuati, devono essere assolutamente distrutti.
    Nelle zone occupate dal nemico bisogna formare reparti di partigiani, a cavallo e a piedi, creare gruppi di distruttori per lottare contro le unità dell'esercito nemico, per scatenare la guerra partigiana ovunque e dappertutto, per far saltare i ponti, le strade, per danneggiare le comunicazioni telefoniche e telegrafiche, per incendiare i boschi, i magazzini, i carriaggi. Nelle zone occupate, creare condizioni insopportabili per il nemico e per tutti i suoi complici, perseguirli e annientarli dovunque, far fallire ogni loro decisione.
    La guerra contro la Germania fascista non può essere considerata una guerra ordinaria. Essa non è soltanto una guerra fra due eserciti. E' nello stesso tempo una grande guerra di tutto il popolo sovietico contro le truppe fasciste tedesche. Lo scopo di questa guerra di tutto il popolo per la difesa della Patria, contro gli oppressori fascisti non è soltanto di eliminare il pericolo che sovrasta la nostra terra, ma anche di aiutare tutti i popoli dell'Europa, che gemono sotto il giogo del fascismo tedesco. In questa grande guerra di liberazione noi non saremo soli. In questa grande guerra avremo alleati fedeli i popoli dell'Europa e dell'America, compreso il popolo tedesco asservito dai caporioni hitleriani. La nostra guerra per la libertà della nostra Patria si fonderà con la lotta dei popoli dell'Europa e dell'America per la loro indipendenza, per le libertà democratiche. Sarà questo un fronte unico dei popoli che sono per la libertà, contro l'asservimento e la minaccia d'asservimento da parte degli eserciti fascisti di Hitler. A questo proposito, lo storico discorso del signor Churchill, primo ministro della Gran Bretagna, sull'aiuto all'Unione Sovietica e la dichiarazione del governo degli Stati Uniti d'America di essere pronto a prestare aiuto al nostro paese, discorso e dichiarazione i quali non possono che suscitare un sentimento di riconoscenza nei cuori dei popoli dell'Unione Sovietica, sono del tutto comprensibili e significativi.
    Compagni! Le nostre forze sono inesauribili. Il tracotante nemico dovrà ben presto convincersene. Insieme all'Esercito rosso si levano alla guerra contro il nemico aggressore molte migliaia di operai, colcosiani, intellettuali. Si leveranno le masse di milioni di uomini del nostro popolo. I lavoratori di Mosca e di Leningrado hanno già iniziato la formazione di una milizia popolare di molte migliaia di uomini a sostegno dell'Esercito rosso. In ogni città minacciata dal pericolo di essere invasa dal nemico, dobbiamo creare una simile milizia popolare, sollevare alla lotta tutti i lavoratori per difendere col proprio petto, nella nostra guerra per la difesa della Patria contro il fascismo tedesco, la propria libertà, il proprio onore, la propria patria.
    Allo scopo di mobilitare rapidamente tutte le forze dei popoli dell'U.R.S.S. per far fronte al nemico che ha aggredito perfidamente la nostra Patria, è stato creato il Comitato di Difesa dello Stato, che concentra ora nelle sue mani tutti i poteri statali. Il Comitato di Difesa dello Stato ha iniziato la sua attività e chiama tutto il popolo ad unirsi attorno al partito di Lenin-Stalin, attorno al Governo sovietico per appoggiare con abnegazione l'Esercito rosso e la Marina rossa, per la disfatta del -nemico, per la vittoria.
    Tutte le nostre forze per sostenere il nostro eroico Esercito rosso, la nostra gloriosa Marina rossa!
    Tutte le forze del popolo per schiacciare il nemico! Avanti, per la nostra vittoria!
    (Edizioni in lingue estere di Mosca – 1946)`)
  }

  ngOnInit() {
    this.service.cercaTuttiRistoranti().subscribe(
      (risultato) => {
        this.elenco = risultato.data
      },
      (errore) => {

        console.log(errore)
      }
    )

  }
}
